export const ADD_PODCAST = "ADD_PODCAST";
export const SET_ERROR = "REMOVE_ERROR";
export const ADD_BOOKMARK = "ADD_BOOKMARK";
export const DELETE_BOOKMARK = "DELETE_BOOKMARK";
export const SET_PLAYING_EPISODE = "SET_PLAYING_EPISODE";
export const TOGGLE_PLAYING_STATUS = "TOGGLE_PLAYING_STATE";
export const SET_PLAYING_POSITION = "SET_PLAYING_POSITION";